# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:1.13

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/vova.solop/pa2020

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - build:backend
  - build:frontend
  - deploy

compile_backend:
  stage: build:backend
  script:
    - cd $CI_PROJECT_DIR/backend  
    - GOOS=linux GOARCH=amd64 go build -v -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/main ./main.go
  artifacts:
    paths:
      - main

compile_frontend:
  stage: build:frontend
  image: node:14.0
  cache:
  paths:
    - node_modules/
  script:
    - cd $CI_PROJECT_DIR/frontend  
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/frontend/build

copy_to_remote:
  stage: deploy
  dependencies:
    - build:backend
    - build:frontend
  script:
    - mkdir -p ~/.ssh/
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$PEM_KEY" >> ~/.ssh/key.pem
    - chmod 400 ~/.ssh/key.pem
    - ssh -i ~/.ssh/key.pem $SERVER_USER@$SERVER_ADDRESS "pm2 stop back; pm2 stop front" 
    - scp -i ~/.ssh/key.pem $CI_PROJECT_DIR/main $SERVER_USER@$SERVER_ADDRESS:pa2020/backend
    - scp -r -i ~/.ssh/key.pem $CI_PROJECT_DIR/frontend/build $SERVER_USER@$SERVER_ADDRESS:pa2020/frontend
    - ssh -i ~/.ssh/key.pem $SERVER_USER@$SERVER_ADDRESS "pm2 restart back; pm2 restart front"     
