version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m2019
      MYSQL_USER: vova
      MYSQL_PASSWORD: vova
    ports:
      - "${MYSQL_PORT}:3306"
    tty: true
    volumes:
      - "./db:/var/lib/mysql:cached"
  front:
    build:
      context: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./frontend/greenlock.d:/usr/app/greenlock.d"
#  pa:
#    build:
#      context: personal_assist
#    ports:
#      - "${PA_PORT}:8887"
##    restart: always
#    depends_on:
#      - mysql
#    volumes:
#      - "./personal_assist/cmd:/cmd"

  app:
    build:
      context: backend
    ports:
      - "${BACK_PORT}:8888"
    restart: always
    depends_on:
      - mysql

  auth:
    build:
      context: auth
    ports:
      - "${AUTH_PORT}:18401"
    restart: always
