export const TOGGLE_COMMENT = 'TOGGLE_COMMENT';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const RELOAD_POST_LIST = 'RELOAD_POST_LIST';
export const RELOAD_TRANS_CATEGORIES_LIST = 'RELOAD_TRANS_CATEGORIES_LIST';
